Bu notebookta numpy öğrenmeye çalışıcam.
yt/brocode'u shadowliycam

Numpy : Numerical Python

Aslında C diliyle yazılmış, bu da onu daha hızlı yapıyor. Nparray pythondaki 
listelerden 10x daha hızlı çalışıyor.

In [4]:
import numpy as np
print(np.__version__)

2.2.5


In [ ]:
# Multidimensional arrays
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(array * 2)
print(array.ndim)
print(array.shape)
print(array[1, 3])

[[ 2  4  6  8]
 [10 12 14 16]]
2
(2, 4)
8


In [24]:
# slicing
array =  np.array([[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12],
          [13,14,15,16]])
# array[start:end:step]
print(array[0:4:2])
# column seçme
print(array[0:2,2:4])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
