Bu notebookta numpy öğrenmeye çalışıcam.
yt/brocode'u shadowliycam

Numpy : Numerical Python

Aslında C diliyle yazılmış, bu da onu daha hızlı yapıyor. Nparray pythondaki 
listelerden 10x daha hızlı çalışıyor.

In [57]:
import numpy as np
print(np.__version__)

2.2.5


In [58]:
# Multidimensional arrays
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(array * 2)
print(array.ndim)
print(array.shape)
print(array[1, 3])

[[ 2  4  6  8]
 [10 12 14 16]]
2
(2, 4)
8


In [59]:
# slicing
array =  np.array([[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12],
          [13,14,15,16]])
# array[start:end:step]
print(array[1:4:2])
# column seçme
print(array[0:4,2:4])

[[ 5  6  7  8]
 [13 14 15 16]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [60]:
# skaler aritmetik
array = np.array([[1,2,3],
          [4,5,6]])
print(array + 2, "\n\n")
print(array - 2, "\n\n")
print(array * 2, "\n\n")
print(array / 2, "\n\n")
print(array ** 2, "\n\n")
print(array % 2, "\n\n")
print(array // 2, "\n\n")
print(array ** 0.5, "\n\n")
array2 = np.array([1,2,3,4,2])
print(array2 == 2)
#turning boolean array to int array
print((array2 == 2).astype(int))

[[3 4 5]
 [6 7 8]] 


[[-1  0  1]
 [ 2  3  4]] 


[[ 2  4  6]
 [ 8 10 12]] 


[[0.5 1.  1.5]
 [2.  2.5 3. ]] 


[[ 1  4  9]
 [16 25 36]] 


[[1 0 1]
 [0 1 0]] 


[[0 1 1]
 [2 2 3]] 


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]] 


[False  True False False  True]
[0 1 0 0 1]


In [61]:
#broadcasting
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)
print(array1 + array2)
print(array1 * array2)
print(array1 - array2)

(1, 4)
(4, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
[[ 0  1  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [-3 -2 -1  0]]


In [62]:
#örnek
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)


(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [63]:
#aggregate functions
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np.sum(array))        
print(np.mean(array))
print(np.std(array))
print(np.var(array)) #variance

print(np.argmax(array))
print(np.argmin(array))

print(np.sum(array, axis=0))
print(np.sum(array, axis=1))

55
5.5
2.8722813232690143
8.25
9
0
[ 7  9 11 13 15]
[15 40]


In [64]:
#filtering
ages = np.array([[18, 22, 35, 41, 25], [16, 17, 18, 19, 20]])
tens = ages[ages < 20]
twenties = ages[(ages >= 20) & (ages < 30)]
print(tens)
print(twenties)
_20s = np.where(ages >= 20, ages, 0)
print(_20s)
print(ages)

[18 16 17 18 19]
[22 25 20]
[[ 0 22 35 41 25]
 [ 0  0  0  0 20]]
[[18 22 35 41 25]
 [16 17 18 19 20]]


In [65]:
#random numbers

rng = np.random.default_rng(seed=42) #random number generator
print(rng.integers(low=1, high=9, size=(10, 10)))


[[1 7 6 4 4 7 1 6 2 1]
 [5 8 6 7 6 7 5 2 7 4]
 [5 3 2 8 7 6 4 7 5 4]
 [4 2 1 5 8 1 7 7 3 6]
 [2 7 6 3 1 8 4 8 6 7]
 [7 2 3 4 4 1 5 2 6 6]
 [8 6 3 8 4 3 8 3 1 4]
 [7 2 4 2 6 4 3 2 5 6]
 [8 4 2 7 6 6 1 3 7 7]
 [4 7 7 4 8 3 2 6 6 2]]


In [66]:
#float numbers
print(np.random.uniform(low=1, high=6))

4.458368834813616


In [67]:
#shuffling
array = np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

TypeError: 'builtin_function_or_method' object is not subscriptable